[package]
name = "mockery"
version = "0.1.0"
authors = ["Louis Capitanchik <contact@louiscap.co>"]

[dependencies]
uuid = { version = "0.6.5", features = ["v4"] }
postgres = "0.15.2"
clap = "2.32.0"
r2d2 = "0.8.2"
r2d2_postgres = "0.14.0"
fake = { version = "1.2.2" }
serde = "1.0.70"
serde_json = "1.0.24"
serde_derive = "1.0.70"
chrono = { version = "0.4.4", features = ["serde"] }
regex = "1.0.2"
lazy_static = "1.0.2"
rayon = "1.0.2"
rayon-hash = "0.3.0"
csv = "1.0.0"
